/**
 * RefineUI System Icons CDN Package Constants
 * 
 * This file contains all the configuration constants and icon metadata
 * used throughout the CDN package.
 */

import { CDNConfig, BuildConfig } from './types';

/** CDN configuration for the package */
export const CDN_CONFIG: CDNConfig = {
  packageName: '@refineui/icon-cdn',
  version: '1.0.0',
  baseUrl: 'https://cdn.jsdelivr.net/npm'
};

/** Build configuration for generating icon files */
export const BUILD_CONFIG: BuildConfig = {
  sourceDir: '../../assets',
  outputDir: './icons',
  sizes: [16, 20, 24, 28, 32, 48],
  styles: ['regular', 'filled']
};

/** Complete icon metadata with all available icons */
export const ICON_METADATA = {
  sizes: [16, 20, 24, 28, 32, 48] as const,
  styles: ['regular', 'filled'] as const,
  icons: [
    'access-time', 'accessibility', 'add', 'add-circle', 'add-square', 'airplane',
    'album', 'alert', 'alert-badge', 'alert-off', 'align-bottom', 'align-center-horizontal',
    'align-center-vertical', 'align-left', 'align-right', 'align-top', 'android',
    'app-folder', 'app-recent', 'app-title', 'appstore', 'autosum', 'backpack',
    'backspace', 'badge', 'balloon', 'bar-chart-horizontal', 'bar-chart-horizontal-descending',
    'bar-chart-vertical', 'bar-chart-vertical-descending', 'barcode-scanner', 'battery-0',
    'battery-10', 'battery-100', 'battery-20', 'battery-30', 'battery-40', 'battery-50',
    'battery-60', 'battery-70', 'battery-80', 'battery-90', 'block', 'bluetooth',
    'blur', 'board', 'book', 'bookmark', 'bug', 'calculator', 'calendar', 'camera',
    'cart', 'carton-box', 'chart', 'chat', 'chat-add', 'chat-empty', 'checkmark',
    'chess', 'chevron-down', 'chevron-left', 'chevron-right', 'chevron-up', 'circle',
    'clipboard', 'clock', 'clock-alarm', 'cloud', 'clover', 'code', 'code-block',
    'comma', 'comment', 'cone', 'contrast', 'control-button', 'cookie', 'copy',
    'couch', 'cpu', 'crop', 'crown', 'css', 'cube', 'cursor', 'cut', 'dart',
    'database', 'delete', 'delete-off', 'dentist', 'desk', 'desktop', 'desktop-mac',
    'dialpad', 'diamond', 'dismiss', 'dismiss-circle', 'dismiss-square', 'doctor',
    'document', 'document-border', 'door', 'drag', 'drawer', 'drop', 'dual-screen',
    'dumbbell', 'dust', 'earth', 'edit', 'edit-off', 'elevator', 'emoji',
    'emoji-angry', 'emoji-cool', 'emoji-grimacing', 'emoji-laugh', 'emoji-meh',
    'emoji-sad', 'emoji-surprise', 'engine', 'equal', 'equal-circle', 'equal-off',
    'error-circle', 'eye', 'eye-off', 'eyedropper', 'eyedropper-off', 'fast-forward',
    'filmstrip', 'filmstrip-off', 'filter', 'fire', 'flag', 'flag-off', 'flash',
    'flash-off', 'flashlight', 'flashlight-off', 'flip-horizontal', 'flip-verticial',
    'folder', 'folder-open', 'frame', 'full-screen-maximize', 'full-screen-minimize',
    'games', 'gantt-chart', 'gas', 'gas-station', 'gavel', 'gif', 'gift', 'gift-card',
    'git', 'glasses', 'global', 'grid', 'guest', 'guitar', 'hammer', 'hard-drive',
    'hat-graduation', 'hd', 'hdr', 'hdr-off', 'headphones', 'headphones-mic', 'headset-vr',
    'heart', 'heart-broken', 'hexagon', 'highlight', 'highway', 'home', 'home-checkmark',
    'hourglass', 'hourglass-half', 'hourglass-one-quarter', 'hourglass-three-quarter',
    'html', 'image', 'image-circle', 'important', 'incognito', 'info', 'ios',
    'ios-arrow-ltr', 'ios-arrow-rtl', 'ios-chevron-ltr', 'ios-chevron-rtl', 'iot',
    'javascript', 'joystick', 'json', 'json-file', 'key', 'key-multiple', 'keyboard',
    'keyboard-backspace', 'keyboard-command', 'keyboard-lock', 'keyboard-off',
    'keyboard-option', 'keyboard-return', 'keyboard-shift', 'keyboard-shift-uppercase',
    'keyboard-tab', 'kiosk', 'kotlin', 'laptop', 'layer', 'lightbulb', 'line',
    'line-dashes', 'line-horizontal-1', 'line-horizontal-1-dashes', 'link', 'location',
    'location-arrow', 'lock-closed', 'lock-open', 'luggage', 'macos', 'mail',
    'mail-read', 'mailbox', 'map', 'markdown', 'math-symbols', 'megaphone', 'mic',
    'moon', 'more-circle', 'more-horizontal', 'more-verticial', 'mouse', 'movie',
    'network-check', 'news', 'next', 'note', 'notebook', 'notepad', 'number-circle-0',
    'number-circle-1', 'number-circle-2', 'number-circle-3', 'number-circle-4',
    'number-circle-5', 'number-circle-6', 'number-circle-7', 'number-circle-8',
    'number-circle-9', 'number-symbol', 'number-symbol-circle', 'number-symbol-square',
    'opacity', 'open', 'open-off', 'options', 'organization', 'organization-horizontal',
    'orientation', 'oval', 'oven', 'padding', 'page-fit', 'paint-brush', 'paint-bucket',
    'parallelogram', 'password', 'pause', 'pause-circle', 'payment', 'payment-wireless',
    'pen', 'pen-off', 'pentagon', 'person', 'person-voice', 'phone', 'piano', 'pin',
    'pipeline', 'play', 'play-circle', 'playstore', 'port-hdmi', 'port-micro-usb',
    'port-usb-a', 'port-usb-c', 'power', 'preview-link', 'previous', 'print',
    'pulse', 'pulse-circle', 'pulse-square', 'python', 'qr-code', 'question',
    'question-circle', 'radio-button', 'ram', 'record', 'record-stop', 'rectangle',
    'refineui', 'rewind', 'rhombus', 'ribbon', 'road', 'road-cone', 'rocket',
    'rotation', 'router', 'rss', 'ruler', 'run', 'save', 'scales', 'script',
    'search', 'send', 'serial-port', 'server', 'server-link', 'server-play',
    'service-bell', 'settings', 'shape-exclude', 'shape-intersect', 'shape-subtract',
    'shape-union', 'shapes', 'share', 'share-android', 'share-ios', 'shell-script',
    'shield', 'shopping-bag', 'sim', 'slide-add', 'slide-content', 'slide-eraser',
    'slide-grid', 'slide-hide', 'slide-layout', 'smartwatch', 'sound-source',
    'spacebar', 'sport-baseball', 'sport-basketball', 'sport-soccer', 'spray-can',
    'square', 'square-hint', 'square-multiple', 'star', 'stop', 'subtract',
    'swift', 'tab', 'tablet', 'tag', 'target', 'temperature', 'tent', 'text',
    'text-align-center', 'text-align-justify', 'text-align-left', 'text-align-right',
    'textbox', 'textbox-align-bottom', 'textbox-align-bottom-center',
    'textbox-align-bottom-left', 'textbox-align-bottom-right', 'textbox-align-center',
    'textbox-align-middle', 'textbox-align-middle-left', 'textbox-align-middle-right',
    'textbox-align-top', 'textbox-align-top-center', 'textbox-align-top-left',
    'textbox-align-top-right', 'thinking', 'ticket', 'timer', 'toggle-left',
    'toggle-multiple', 'toggle-right', 'toolbox', 'trophy', 'tv', 'typescript',
    'umbrella', 'usb', 'usb-cable', 'verified', 'video', 'video-clip',
    'video-play-pause', 'voicemail', 'vote', 'walkie-talkie', 'wallet', 'wand',
    'warning', 'washer', 'water', 'weather-blowing-snow', 'weather-cloudy',
    'weather-rain', 'weather-snow', 'weather-snowflake', 'weather-sunny',
    'weather-thunderstorm', 'web', 'wifi-1', 'wifi-2', 'wifi-3', 'wifi-4',
    'windows', 'wrench', 'xray', 'zoom', 'zoom-in', 'zoom-out'
  ]
} as const;

/** Icon name mapping from display names to hyphenated format (for CDN paths) */
export const ICON_NAME_MAPPING: Record<string, string> = {
  'access-time': 'access-time',
  'accessibility': 'accessibility',
  'add': 'add',
  'add-circle': 'add-circle',
  'add-square': 'add-square',
  'airplane': 'airplane',
  'album': 'album',
  'alert': 'alert',
  'alert-badge': 'alert-badge',
  'alert-off': 'alert-off',
  'align-bottom': 'align-bottom',
  'align-center-horizontal': 'align-center-horizontal',
  'align-center-vertical': 'align-center-vertical',
  'align-left': 'align-left',
  'align-right': 'align-right',
  'align-top': 'align-top',
  'android': 'android',
  'app-folder': 'app-folder',
  'app-recent': 'app-recent',
  'app-title': 'app-title',
  'appstore': 'appstore',
  'autosum': 'autosum',
  'backpack': 'backpack',
  'backspace': 'backspace',
  'badge': 'badge',
  'balloon': 'balloon',
  'bar-chart-horizontal': 'bar-chart-horizontal',
  'bar-chart-horizontal-descending': 'bar-chart-horizontal-descending',
  'bar-chart-vertical': 'bar-chart-vertical',
  'bar-chart-vertical-descending': 'bar-chart-vertical-descending',
  'barcode-scanner': 'barcode-scanner',
  'battery-0': 'battery-0',
  'battery-10': 'battery-10',
  'battery-100': 'battery-100',
  'battery-20': 'battery-20',
  'battery-30': 'battery-30',
  'battery-40': 'battery-40',
  'battery-50': 'battery-50',
  'battery-60': 'battery-60',
  'battery-70': 'battery-70',
  'battery-80': 'battery-80',
  'battery-90': 'battery-90',
  'block': 'block',
  'bluetooth': 'bluetooth',
  'blur': 'blur',
  'board': 'board',
  'book': 'book',
  'bookmark': 'bookmark',
  'bug': 'bug',
  'calculator': 'calculator',
  'calendar': 'calendar',
  'camera': 'camera',
  'cart': 'cart',
  'carton-box': 'carton-box',
  'chart': 'chart',
  'chat': 'chat',
  'chat-add': 'chat-add',
  'chat-empty': 'chat-empty',
  'checkmark': 'checkmark',
  'chess': 'chess',
  'chevron-down': 'chevron-down',
  'chevron-left': 'chevron-left',
  'chevron-right': 'chevron-right',
  'chevron-up': 'chevron-up',
  'circle': 'circle',
  'clipboard': 'clipboard',
  'clock': 'clock',
  'clock-alarm': 'clock-alarm',
  'cloud': 'cloud',
  'clover': 'clover',
  'code': 'code',
  'code-block': 'code-block',
  'comma': 'comma',
  'comment': 'comment',
  'cone': 'cone',
  'contrast': 'contrast',
  'control-button': 'control-button',
  'cookie': 'cookie',
  'copy': 'copy',
  'couch': 'couch',
  'cpu': 'cpu',
  'crop': 'crop',
  'crown': 'crown',
  'css': 'css',
  'cube': 'cube',
  'cursor': 'cursor',
  'cut': 'cut',
  'dart': 'dart',
  'database': 'database',
  'delete': 'delete',
  'delete-off': 'delete-off',
  'dentist': 'dentist',
  'desk': 'desk',
  'desktop': 'desktop',
  'desktop-mac': 'desktop-mac',
  'dialpad': 'dialpad',
  'diamond': 'diamond',
  'dismiss': 'dismiss',
  'dismiss-circle': 'dismiss-circle',
  'dismiss-square': 'dismiss-square',
  'doctor': 'doctor',
  'document': 'document',
  'document-border': 'document-border',
  'door': 'door',
  'drag': 'drag',
  'drawer': 'drawer',
  'drop': 'drop',
  'dual-screen': 'dual-screen',
  'dumbbell': 'dumbbell',
  'dust': 'dust',
  'earth': 'earth',
  'edit': 'edit',
  'edit-off': 'edit-off',
  'elevator': 'elevator',
  'emoji': 'emoji',
  'emoji-angry': 'emoji-angry',
  'emoji-cool': 'emoji-cool',
  'emoji-grimacing': 'emoji-grimacing',
  'emoji-laugh': 'emoji-laugh',
  'emoji-meh': 'emoji-meh',
  'emoji-sad': 'emoji-sad',
  'emoji-surprise': 'emoji-surprise',
  'engine': 'engine',
  'equal': 'equal',
  'equal-circle': 'equal-circle',
  'equal-off': 'equal-off',
  'error-circle': 'error-circle',
  'eye': 'eye',
  'eye-off': 'eye-off',
  'eyedropper': 'eyedropper',
  'eyedropper-off': 'eyedropper-off',
  'fast-forward': 'fast-forward',
  'filmstrip': 'filmstrip',
  'filmstrip-off': 'filmstrip-off',
  'filter': 'filter',
  'fire': 'fire',
  'flag': 'flag',
  'flag-off': 'flag-off',
  'flash': 'flash',
  'flash-off': 'flash-off',
  'flashlight': 'flashlight',
  'flashlight-off': 'flashlight-off',
  'flip-horizontal': 'flip-horizontal',
  'flip-verticial': 'flip-verticial',
  'folder': 'folder',
  'folder-open': 'folder-open',
  'frame': 'frame',
  'full-screen-maximize': 'full-screen-maximize',
  'full-screen-minimize': 'full-screen-minimize',
  'games': 'games',
  'gantt-chart': 'gantt-chart',
  'gas': 'gas',
  'gas-station': 'gas-station',
  'gavel': 'gavel',
  'gif': 'gif',
  'gift': 'gift',
  'gift-card': 'gift-card',
  'git': 'git',
  'glasses': 'glasses',
  'global': 'global',
  'grid': 'grid',
  'guest': 'guest',
  'guitar': 'guitar',
  'hammer': 'hammer',
  'hard-drive': 'hard-drive',
  'hat-graduation': 'hat-graduation',
  'hd': 'hd',
  'hdr': 'hdr',
  'hdr-off': 'hdr-off',
  'headphones': 'headphones',
  'headphones-mic': 'headphones-mic',
  'headset-vr': 'headset-vr',
  'heart': 'heart',
  'heart-broken': 'heart-broken',
  'hexagon': 'hexagon',
  'highlight': 'highlight',
  'highway': 'highway',
  'home': 'home',
  'home-checkmark': 'home-checkmark',
  'hourglass': 'hourglass',
  'hourglass-half': 'hourglass-half',
  'hourglass-one-quarter': 'hourglass-one-quarter',
  'hourglass-three-quarter': 'hourglass-three-quarter',
  'html': 'html',
  'image': 'image',
  'image-circle': 'image-circle',
  'important': 'important',
  'incognito': 'incognito',
  'info': 'info',
  'ios': 'ios',
  'ios-arrow-ltr': 'ios-arrow-ltr',
  'ios-arrow-rtl': 'ios-arrow-rtl',
  'ios-chevron-ltr': 'ios-chevron-ltr',
  'ios-chevron-rtl': 'ios-chevron-rtl',
  'iot': 'iot',
  'javascript': 'javascript',
  'joystick': 'joystick',
  'json': 'json',
  'json-file': 'json-file',
  'key': 'key',
  'key-multiple': 'key-multiple',
  'keyboard': 'keyboard',
  'keyboard-backspace': 'keyboard-backspace',
  'keyboard-command': 'keyboard-command',
  'keyboard-lock': 'keyboard-lock',
  'keyboard-off': 'keyboard-off',
  'keyboard-option': 'keyboard-option',
  'keyboard-return': 'keyboard-return',
  'keyboard-shift': 'keyboard-shift',
  'keyboard-shift-uppercase': 'keyboard-shift-uppercase',
  'keyboard-tab': 'keyboard-tab',
  'kiosk': 'kiosk',
  'kotlin': 'kotlin',
  'laptop': 'laptop',
  'layer': 'layer',
  'lightbulb': 'lightbulb',
  'line': 'line',
  'line-dashes': 'line-dashes',
  'line-horizontal-1': 'line-horizontal-1',
  'line-horizontal-1-dashes': 'line-horizontal-1-dashes',
  'link': 'link',
  'local-language': 'local-language',
  'location': 'location',
  'location-arrow': 'location-arrow',
  'lock-closed': 'lock-closed',
  'lock-open': 'lock-open',
  'luggage': 'luggage',
  'macos': 'macos',
  'mail': 'mail',
  'mail-read': 'mail-read',
  'mailbox': 'mailbox',
  'map': 'map',
  'markdown': 'markdown',
  'math-symbols': 'math-symbols',
  'megaphone': 'megaphone',
  'mic': 'mic',
  'moon': 'moon',
  'more-circle': 'more-circle',
  'more-horizontal': 'more-horizontal',
  'more-verticial': 'more-verticial',
  'mouse': 'mouse',
  'movie': 'movie',
  'network-check': 'network-check',
  'news': 'news',
  'next': 'next',
  'note': 'note',
  'notebook': 'notebook',
  'notepad': 'notepad',
  'number-circle-0': 'number-circle-0',
  'number-circle-1': 'number-circle-1',
  'number-circle-2': 'number-circle-2',
  'number-circle-3': 'number-circle-3',
  'number-circle-4': 'number-circle-4',
  'number-circle-5': 'number-circle-5',
  'number-circle-6': 'number-circle-6',
  'number-circle-7': 'number-circle-7',
  'number-circle-8': 'number-circle-8',
  'number-circle-9': 'number-circle-9',
  'number-symbol': 'number-symbol',
  'number-symbol-circle': 'number-symbol-circle',
  'number-symbol-square': 'number-symbol-square',
  'opacity': 'opacity',
  'open': 'open',
  'open-off': 'open-off',
  'options': 'options',
  'organization': 'organization',
  'organization-horizontal': 'organization-horizontal',
  'orientation': 'orientation',
  'oval': 'oval',
  'oven': 'oven',
  'padding': 'padding',
  'page-fit': 'page-fit',
  'paint-brush': 'paint-brush',
  'paint-bucket': 'paint-bucket',
  'parallelogram': 'parallelogram',
  'password': 'password',
  'pause': 'pause',
  'pause-circle': 'pause-circle',
  'payment': 'payment',
  'payment-wireless': 'payment-wireless',
  'pen': 'pen',
  'pen-off': 'pen-off',
  'pentagon': 'pentagon',
  'person': 'person',
  'person-voice': 'person-voice',
  'phone': 'phone',
  'piano': 'piano',
  'pin': 'pin',
  'pipeline': 'pipeline',
  'play': 'play',
  'play-circle': 'play-circle',
  'playstore': 'playstore',
  'port-hdmi': 'port-hdmi',
  'port-micro-usb': 'port-micro-usb',
  'port-usb-a': 'port-usb-a',
  'port-usb-c': 'port-usb-c',
  'power': 'power',
  'preview-link': 'preview-link',
  'previous': 'previous',
  'print': 'print',
  'pulse': 'pulse',
  'pulse-circle': 'pulse-circle',
  'pulse-square': 'pulse-square',
  'python': 'python',
  'qr-code': 'qr-code',
  'question': 'question',
  'question-circle': 'question-circle',
  'radio-button': 'radio-button',
  'ram': 'ram',
  'record': 'record',
  'record-stop': 'record-stop',
  'rectangle': 'rectangle',
  'refineui': 'refineui',
  'rewind': 'rewind',
  'rhombus': 'rhombus',
  'ribbon': 'ribbon',
  'road': 'road',
  'road-cone': 'road-cone',
  'rocket': 'rocket',
  'rotation': 'rotation',
  'router': 'router',
  'rss': 'rss',
  'ruler': 'ruler',
  'run': 'run',
  'save': 'save',
  'scales': 'scales',
  'script': 'script',
  'search': 'search',
  'send': 'send',
  'serial-port': 'serial-port',
  'server': 'server',
  'server-link': 'server-link',
  'server-play': 'server-play',
  'service-bell': 'service-bell',
  'settings': 'settings',
  'shape-exclude': 'shape-exclude',
  'shape-intersect': 'shape-intersect',
  'shape-subtract': 'shape-subtract',
  'shape-union': 'shape-union',
  'shapes': 'shapes',
  'share': 'share',
  'share-android': 'share-android',
  'share-ios': 'share-ios',
  'shell-script': 'shell-script',
  'shield': 'shield',
  'shopping-bag': 'shopping-bag',
  'sim': 'sim',
  'slide-add': 'slide-add',
  'slide-content': 'slide-content',
  'slide-eraser': 'slide-eraser',
  'slide-grid': 'slide-grid',
  'slide-hide': 'slide-hide',
  'slide-layout': 'slide-layout',
  'smartwatch': 'smartwatch',
  'sound-source': 'sound-source',
  'spacebar': 'spacebar',
  'sport-baseball': 'sport-baseball',
  'sport-basketball': 'sport-basketball',
  'sport-soccer': 'sport-soccer',
  'spray-can': 'spray-can',
  'square': 'square',
  'square-hint': 'square-hint',
  'square-multiple': 'square-multiple',
  'star': 'star',
  'stop': 'stop',
  'subtract': 'subtract',
  'swift': 'swift',
  'tab': 'tab',
  'tablet': 'tablet',
  'tag': 'tag',
  'target': 'target',
  'temperature': 'temperature',
  'tent': 'tent',
  'text': 'text',
  'text-align-center': 'text-align-center',
  'text-align-justify': 'text-align-justify',
  'text-align-left': 'text-align-left',
  'text-align-right': 'text-align-right',
  'textbox': 'textbox',
  'textbox-align-bottom': 'textbox-align-bottom',
  'textbox-align-bottom-center': 'textbox-align-bottom-center',
  'textbox-align-bottom-left': 'textbox-align-bottom-left',
  'textbox-align-bottom-right': 'textbox-align-bottom-right',
  'textbox-align-center': 'textbox-align-center',
  'textbox-align-middle': 'textbox-align-middle',
  'textbox-align-middle-left': 'textbox-align-middle-left',
  'textbox-align-middle-right': 'textbox-align-middle-right',
  'textbox-align-top': 'textbox-align-top',
  'textbox-align-top-center': 'textbox-align-top-center',
  'textbox-align-top-left': 'textbox-align-top-left',
  'textbox-align-top-right': 'textbox-align-top-right',
  'thinking': 'thinking',
  'ticket': 'ticket',
  'timer': 'timer',
  'toggle-left': 'toggle-left',
  'toggle-multiple': 'toggle-multiple',
  'toggle-right': 'toggle-right',
  'toolbox': 'toolbox',
  'trophy': 'trophy',
  'tv': 'tv',
  'typescript': 'typescript',
  'umbrella': 'umbrella',
  'usb': 'usb',
  'usb-cable': 'usb-cable',
  'verified': 'verified',
  'video': 'video',
  'video-clip': 'video-clip',
  'video-play-pause': 'video-play-pause',
  'voicemail': 'voicemail',
  'vote': 'vote',
  'walkie-talkie': 'walkie-talkie',
  'wallet': 'wallet',
  'wand': 'wand',
  'warning': 'warning',
  'washer': 'washer',
  'water': 'water',
  'weather-blowing-snow': 'weather-blowing-snow',
  'weather-cloudy': 'weather-cloudy',
  'weather-rain': 'weather-rain',
  'weather-snow': 'weather-snow',
  'weather-snowflake': 'weather-snowflake',
  'weather-sunny': 'weather-sunny',
  'weather-thunderstorm': 'weather-thunderstorm',
  'web': 'web',
  'wifi-1': 'wifi-1',
  'wifi-2': 'wifi-2',
  'wifi-3': 'wifi-3',
  'wifi-4': 'wifi-4',
  'windows': 'windows',
  'wrench': 'wrench',
  'xray': 'xray',
  'zoom': 'zoom',
  'zoom-in': 'zoom-in',
  'zoom-out': 'zoom_out',
};
