/**
 * RefineUI System Icons CDN Package Constants
 * 
 * This file contains all the configuration constants and icon metadata
 * used throughout the CDN package.
 */

import { CDNConfig, BuildConfig } from './types';

/** CDN configuration for the package */
export const CDN_CONFIG: CDNConfig = {
  packageName: '@refineui/icon-cdn',
  version: '1.0.0',
  baseUrl: 'https://cdn.jsdelivr.net/npm'
};

/** Build configuration for generating icon files */
export const BUILD_CONFIG: BuildConfig = {
  sourceDir: '../../assets',
  outputDir: './icons',
  sizes: [16, 20, 24, 28, 32, 48],
  styles: ['regular', 'filled']
};

/** Complete icon metadata with all available icons */
export const ICON_METADATA = {
  sizes: [16, 20, 24, 28, 32, 48] as const,
  styles: ['regular', 'filled'] as const,
  icons: [
    'access-time', 'accessibility', 'add', 'add-circle', 'add-square', 'airplane',
    'album', 'alert', 'alert-badge', 'alert-off', 'align-bottom', 'align-center-horizontal',
    'align-center-vertical', 'align-left', 'align-right', 'align-top', 'android',
    'app-folder', 'app-recent', 'app-title', 'appstore', 'autosum', 'backpack',
    'backspace', 'badge', 'balloon', 'bar-chart-horizontal', 'bar-chart-horizontal-descending',
    'bar-chart-vertical', 'bar-chart-vertical-descending', 'barcode-scanner', 'battery-0',
    'battery-10', 'battery-100', 'battery-20', 'battery-30', 'battery-40', 'battery-50',
    'battery-60', 'battery-70', 'battery-80', 'battery-90', 'block', 'bluetooth',
    'blur', 'board', 'book', 'bookmark', 'bug', 'calculator', 'calendar', 'camera',
    'cart', 'carton-box', 'chart', 'chat', 'chat-add', 'chat-empty', 'checkmark',
    'chess', 'chevron-down', 'chevron-left', 'chevron-right', 'chevron-up', 'circle',
    'clipboard', 'clock', 'clock-alarm', 'cloud', 'clover', 'code', 'code-block',
    'comma', 'comment', 'cone', 'contrast', 'control-button', 'cookie', 'copy',
    'couch', 'cpu', 'crop', 'crown', 'css', 'cube', 'cursor', 'cut', 'dart',
    'database', 'delete', 'delete-off', 'dentist', 'desk', 'desktop', 'desktop-mac',
    'dialpad', 'diamond', 'dismiss', 'dismiss-circle', 'dismiss-square', 'doctor',
    'document', 'document-border', 'door', 'drag', 'drawer', 'drop', 'dual-screen',
    'dumbbell', 'dust', 'earth', 'edit', 'edit-off', 'elevator', 'emoji',
    'emoji-angry', 'emoji-cool', 'emoji-grimacing', 'emoji-laugh', 'emoji-meh',
    'emoji-sad', 'emoji-surprise', 'engine', 'equal', 'equal-circle', 'equal-off',
    'error-circle', 'eye', 'eye-off', 'eyedropper', 'eyedropper-off', 'fast-forward',
    'filmstrip', 'filmstrip-off', 'filter', 'fire', 'flag', 'flag-off', 'flash',
    'flash-off', 'flashlight', 'flashlight-off', 'flip-horizontal', 'flip-verticial',
    'folder', 'folder-open', 'frame', 'full-screen-maximize', 'full-screen-minimize',
    'games', 'gantt-chart', 'gas', 'gas-station', 'gavel', 'gif', 'gift', 'gift-card',
    'git', 'glasses', 'global', 'grid', 'guest', 'guitar', 'hammer', 'hard-drive',
    'hat-graduation', 'hd', 'hdr', 'hdr-off', 'headphones', 'headphones-mic', 'headset-vr',
    'heart', 'heart-broken', 'hexagon', 'highlight', 'highway', 'home', 'home-checkmark',
    'hourglass', 'hourglass-half', 'hourglass-one-quarter', 'hourglass-three-quarter',
    'html', 'image', 'image-circle', 'important', 'incognito', 'info', 'ios',
    'ios-arrow-ltr', 'ios-arrow-rtl', 'ios-chevron-ltr', 'ios-chevron-rtl', 'iot',
    'javascript', 'joystick', 'json', 'json-file', 'key', 'key-multiple', 'keyboard',
    'keyboard-backspace', 'keyboard-command', 'keyboard-lock', 'keyboard-off',
    'keyboard-option', 'keyboard-return', 'keyboard-shift', 'keyboard-shift-uppercase',
    'keyboard-tab', 'kiosk', 'kotlin', 'laptop', 'layer', 'lightbulb', 'line',
    'line-dashes', 'line-horizontal-1', 'line-horizontal-1-dashes', 'link', 'location',
    'location-arrow', 'lock-closed', 'lock-open', 'luggage', 'macos', 'mail',
    'mail-read', 'mailbox', 'map', 'markdown', 'math-symbols', 'megaphone', 'mic',
    'moon', 'more-circle', 'more-horizontal', 'more-verticial', 'mouse', 'movie',
    'network-check', 'news', 'next', 'note', 'notebook', 'notepad', 'number-circle-0',
    'number-circle-1', 'number-circle-2', 'number-circle-3', 'number-circle-4',
    'number-circle-5', 'number-circle-6', 'number-circle-7', 'number-circle-8',
    'number-circle-9', 'number-symbol', 'number-symbol-circle', 'number-symbol-square',
    'opacity', 'open', 'open-off', 'options', 'organization', 'organization-horizontal',
    'orientation', 'oval', 'oven', 'padding', 'page-fit', 'paint-brush', 'paint-bucket',
    'parallelogram', 'password', 'pause', 'pause-circle', 'payment', 'payment-wireless',
    'pen', 'pen-off', 'pentagon', 'person', 'person-voice', 'phone', 'piano', 'pin',
    'pipeline', 'play', 'play-circle', 'playstore', 'port-hdmi', 'port-micro-usb',
    'port-usb-a', 'port-usb-c', 'power', 'preview-link', 'previous', 'print',
    'pulse', 'pulse-circle', 'pulse-square', 'python', 'qr-code', 'question',
    'question-circle', 'radio-button', 'ram', 'record', 'record-stop', 'rectangle',
    'refineui', 'rewind', 'rhombus', 'ribbon', 'road', 'road-cone', 'rocket',
    'rotation', 'router', 'rss', 'ruler', 'run', 'save', 'scales', 'script',
    'search', 'send', 'serial-port', 'server', 'server-link', 'server-play',
    'service-bell', 'settings', 'shape-exclude', 'shape-intersect', 'shape-subtract',
    'shape-union', 'shapes', 'share', 'share-android', 'share-ios', 'shell-script',
    'shield', 'shopping-bag', 'sim', 'slide-add', 'slide-content', 'slide-eraser',
    'slide-grid', 'slide-hide', 'slide-layout', 'smartwatch', 'sound-source',
    'spacebar', 'sport-baseball', 'sport-basketball', 'sport-soccer', 'spray-can',
    'square', 'square-hint', 'square-multiple', 'star', 'stop', 'subtract',
    'swift', 'tab', 'tablet', 'tag', 'target', 'temperature', 'tent', 'text',
    'text-align-center', 'text-align-justify', 'text-align-left', 'text-align-right',
    'textbox', 'textbox-align-bottom', 'textbox-align-bottom-center',
    'textbox-align-bottom-left', 'textbox-align-bottom-right', 'textbox-align-center',
    'textbox-align-middle', 'textbox-align-middle-left', 'textbox-align-middle-right',
    'textbox-align-top', 'textbox-align-top-center', 'textbox-align-top-left',
    'textbox-align-top-right', 'thinking', 'ticket', 'timer', 'toggle-left',
    'toggle-multiple', 'toggle-right', 'toolbox', 'trophy', 'tv', 'typescript',
    'umbrella', 'usb', 'usb-cable', 'verified', 'video', 'video-clip',
    'video-play-pause', 'voicemail', 'vote', 'walkie-talkie', 'wallet', 'wand',
    'warning', 'washer', 'water', 'weather-blowing-snow', 'weather-cloudy',
    'weather-rain', 'weather-snow', 'weather-snowflake', 'weather-sunny',
    'weather-thunderstorm', 'web', 'wifi-1', 'wifi-2', 'wifi-3', 'wifi-4',
    'windows', 'wrench', 'xray', 'zoom', 'zoom-in', 'zoom-out'
  ]
} as const;

/** Icon name mapping from display names to hyphenated format (for CDN paths) */
export const ICON_NAME_MAPPING: Record<string, string> = {
  'Access time': 'access-time',
  'Accessibility': 'accessibility',
  'Add': 'add',
  'Add circle': 'add-circle',
  'Add square': 'add-square',
  'Airplane': 'airplane',
  'Album': 'album',
  'Alert': 'alert',
  'Alert badge': 'alert-badge',
  'Alert off': 'alert-off',
  'Align bottom': 'align-bottom',
  'Align center horizontal': 'align-center-horizontal',
  'Align center vertical': 'align-center-vertical',
  'Align left': 'align-left',
  'Align right': 'align-right',
  'Align top': 'align-top',
  'Android': 'android',
  'App folder': 'app-folder',
  'App recent': 'app-recent',
  'App title': 'app-title',
  'Appstore': 'appstore',
  'Autosum': 'autosum',
  'Backpack': 'backpack',
  'Backspace': 'backspace',
  'Badge': 'badge',
  'Balloon': 'balloon',
  'Bar chart horizontal': 'bar-chart-horizontal',
  'Bar chart horizontal descending': 'bar-chart-horizontal-descending',
  'Bar chart vertical': 'bar-chart-vertical',
  'Bar chart vertical descending': 'bar-chart-vertical-descending',
  'Barcode scanner': 'barcode-scanner',
  'Battery 0': 'battery-0',
  'Battery 10': 'battery-10',
  'Battery 100': 'battery-100',
  'Battery 20': 'battery-20',
  'Battery 30': 'battery-30',
  'Battery 40': 'battery-40',
  'Battery 50': 'battery-50',
  'Battery 60': 'battery-60',
  'Battery 70': 'battery-70',
  'Battery 80': 'battery-80',
  'Battery 90': 'battery-90',
  'Block': 'block',
  'Bluetooth': 'bluetooth',
  'Blur': 'blur',
  'Board': 'board',
  'Book': 'book',
  'Bookmark': 'bookmark',
  'Bug': 'bug',
  'Calculator': 'calculator',
  'Calendar': 'calendar',
  'Camera': 'camera',
  'Cart': 'cart',
  'Carton box': 'carton-box',
  'Chart': 'chart',
  'Chat': 'chat',
  'Chat add': 'chat-add',
  'Chat empty': 'chat-empty',
  'Checkmark': 'checkmark',
  'Chess': 'chess',
  'Chevron down': 'chevron-down',
  'Chevron left': 'chevron-left',
  'Chevron right': 'chevron-right',
  'Chevron up': 'chevron-up',
  'Circle': 'circle',
  'Clipboard': 'clipboard',
  'Clock': 'clock',
  'Clock alarm': 'clock-alarm',
  'Cloud': 'cloud',
  'Clover': 'clover',
  'Code': 'code',
  'Code block': 'code-block',
  'Comma': 'comma',
  'Comment': 'comment',
  'Cone': 'cone',
  'Contrast': 'contrast',
  'Control button': 'control-button',
  'Cookie': 'cookie',
  'Copy': 'copy',
  'Couch': 'couch',
  'Cpu': 'cpu',
  'Crop': 'crop',
  'Crown': 'crown',
  'Css': 'css',
  'Cube': 'cube',
  'Cursor': 'cursor',
  'Cut': 'cut',
  'Dart': 'dart',
  'Database': 'database',
  'Delete': 'delete',
  'Delete off': 'delete-off',
  'Dentist': 'dentist',
  'Desk': 'desk',
  'Desktop': 'desktop',
  'Desktop mac': 'desktop-mac',
  'Dialpad': 'dialpad',
  'Diamond': 'diamond',
  'Dismiss': 'dismiss',
  'Dismiss circle': 'dismiss-circle',
  'Dismiss square': 'dismiss-square',
  'Doctor': 'doctor',
  'Document': 'document',
  'Document border': 'document-border',
  'Door': 'door',
  'Drag': 'drag',
  'Drawer': 'drawer',
  'Drop': 'drop',
  'Dual screen': 'dual-screen',
  'Dumbbell': 'dumbbell',
  'Dust': 'dust',
  'Earth': 'earth',
  'Edit': 'edit',
  'Edit off': 'edit-off',
  'Elevator': 'elevator',
  'Emoji': 'emoji',
  'Emoji angry': 'emoji-angry',
  'Emoji cool': 'emoji-cool',
  'Emoji grimacing': 'emoji-grimacing',
  'Emoji laugh': 'emoji-laugh',
  'Emoji meh': 'emoji-meh',
  'Emoji sad': 'emoji-sad',
  'Emoji surprise': 'emoji-surprise',
  'Engine': 'engine',
  'Equal': 'equal',
  'Equal circle': 'equal-circle',
  'Equal off': 'equal-off',
  'Error circle': 'error-circle',
  'Eye': 'eye',
  'Eye off': 'eye-off',
  'Eyedropper': 'eyedropper',
  'Eyedropper off': 'eyedropper-off',
  'Fast forward': 'fast-forward',
  'Filmstrip': 'filmstrip',
  'Filmstrip off': 'filmstrip-off',
  'Filter': 'filter',
  'Fire': 'fire',
  'Flag': 'flag',
  'Flag off': 'flag-off',
  'Flash': 'flash',
  'Flash off': 'flash-off',
  'Flashlight': 'flashlight',
  'Flashlight off': 'flashlight-off',
  'Flip horizontal': 'flip-horizontal',
  'Flip verticial': 'flip-verticial',
  'Folder': 'folder',
  'Folder open': 'folder-open',
  'Frame': 'frame',
  'Full screen maximize': 'full-screen-maximize',
  'Full screen minimize': 'full-screen-minimize',
  'Games': 'games',
  'Gantt chart': 'gantt-chart',
  'Gas': 'gas',
  'Gas station': 'gas-station',
  'Gavel': 'gavel',
  'Gif': 'gif',
  'Gift': 'gift',
  'Gift card': 'gift-card',
  'Git': 'git',
  'Glasses': 'glasses',
  'Global': 'global',
  'Grid': 'grid',
  'Guest': 'guest',
  'Guitar': 'guitar',
  'Hammer': 'hammer',
  'Hard drive': 'hard-drive',
  'Hat graduation': 'hat-graduation',
  'Hd': 'hd',
  'Hdr': 'hdr',
  'Hdr off': 'hdr-off',
  'Headphones': 'headphones',
  'Headphones mic': 'headphones-mic',
  'Headset vr': 'headset-vr',
  'Heart': 'heart',
  'Heart broken': 'heart-broken',
  'Hexagon': 'hexagon',
  'Highlight': 'highlight',
  'Highway': 'highway',
  'Home': 'home',
  'Home checkmark': 'home-checkmark',
  'Hourglass': 'hourglass',
  'Hourglass half': 'hourglass-half',
  'Hourglass one quarter': 'hourglass-one-quarter',
  'Hourglass three quarter': 'hourglass-three-quarter',
  'Html': 'html',
  'Image': 'image',
  'Image circle': 'image-circle',
  'Important': 'important',
  'Incognito': 'incognito',
  'Info': 'info',
  'Ios': 'ios',
  'Ios arrow ltr': 'ios-arrow-ltr',
  'Ios arrow rtl': 'ios-arrow-rtl',
  'Ios chevron ltr': 'ios-chevron-ltr',
  'Ios chevron rtl': 'ios-chevron-rtl',
  'Iot': 'iot',
  'Javascript': 'javascript',
  'Joystick': 'joystick',
  'Json': 'json',
  'Json file': 'json-file',
  'Key': 'key',
  'Key multiple': 'key-multiple',
  'Keyboard': 'keyboard',
  'Keyboard backspace': 'keyboard-backspace',
  'Keyboard command': 'keyboard-command',
  'Keyboard lock': 'keyboard-lock',
  'Keyboard off': 'keyboard-off',
  'Keyboard option': 'keyboard-option',
  'Keyboard return': 'keyboard-return',
  'Keyboard shift': 'keyboard-shift',
  'Keyboard shift uppercase': 'keyboard-shift-uppercase',
  'Keyboard tab': 'keyboard-tab',
  'Kiosk': 'kiosk',
  'Kotlin': 'kotlin',
  'Laptop': 'laptop',
  'Layer': 'layer',
  'Lightbulb': 'lightbulb',
  'Line': 'line',
  'Line dashes': 'line-dashes',
  'Line horizontal 1': 'line-horizontal-1',
  'Line horizontal 1 dashes': 'line-horizontal-1-dashes',
  'Link': 'link',
  'Local language': 'local-language',
  'Location': 'location',
  'Location arrow': 'location-arrow',
  'Lock closed': 'lock-closed',
  'Lock open': 'lock-open',
  'Luggage': 'luggage',
  'Macos': 'macos',
  'Mail': 'mail',
  'Mail read': 'mail-read',
  'Mailbox': 'mailbox',
  'Map': 'map',
  'Markdown': 'markdown',
  'Math symbols': 'math-symbols',
  'Megaphone': 'megaphone',
  'Mic': 'mic',
  'Moon': 'moon',
  'More circle': 'more-circle',
  'More horizontal': 'more-horizontal',
  'More verticial': 'more-verticial',
  'Mouse': 'mouse',
  'Movie': 'movie',
  'Network check': 'network-check',
  'News': 'news',
  'Next': 'next',
  'Note': 'note',
  'Notebook': 'notebook',
  'Notepad': 'notepad',
  'Number circle 0': 'number-circle-0',
  'Number circle 1': 'number-circle-1',
  'Number circle 2': 'number-circle-2',
  'Number circle 3': 'number-circle-3',
  'Number circle 4': 'number-circle-4',
  'Number circle 5': 'number-circle-5',
  'Number circle 6': 'number-circle-6',
  'Number circle 7': 'number-circle-7',
  'Number circle 8': 'number-circle-8',
  'Number circle 9': 'number-circle-9',
  'Number symbol': 'number-symbol',
  'Number symbol circle': 'number-symbol-circle',
  'Number symbol square': 'number-symbol-square',
  'Opacity': 'opacity',
  'Open': 'open',
  'Open off': 'open-off',
  'Options': 'options',
  'Organization': 'organization',
  'Organization horizontal': 'organization-horizontal',
  'Orientation': 'orientation',
  'Oval': 'oval',
  'Oven': 'oven',
  'Padding': 'padding',
  'Page fit': 'page-fit',
  'Paint brush': 'paint-brush',
  'Paint bucket': 'paint-bucket',
  'Parallelogram': 'parallelogram',
  'Password': 'password',
  'Pause': 'pause',
  'Pause circle': 'pause-circle',
  'Payment': 'payment',
  'Payment wireless': 'payment-wireless',
  'Pen': 'pen',
  'Pen off': 'pen-off',
  'Pentagon': 'pentagon',
  'Person': 'person',
  'Person voice': 'person-voice',
  'Phone': 'phone',
  'Piano': 'piano',
  'Pin': 'pin',
  'Pipeline': 'pipeline',
  'Play': 'play',
  'Play circle': 'play-circle',
  'Playstore': 'playstore',
  'Port hdmi': 'port-hdmi',
  'Port micro usb': 'port-micro-usb',
  'Port usb a': 'port-usb-a',
  'Port usb c': 'port-usb-c',
  'Power': 'power',
  'Preview link': 'preview-link',
  'Previous': 'previous',
  'Print': 'print',
  'Pulse': 'pulse',
  'Pulse circle': 'pulse-circle',
  'Pulse square': 'pulse-square',
  'Python': 'python',
  'Qr code': 'qr-code',
  'Question': 'question',
  'Question circle': 'question-circle',
  'Radio button': 'radio-button',
  'Ram': 'ram',
  'Record': 'record',
  'Record stop': 'record-stop',
  'Rectangle': 'rectangle',
  'Refineui': 'refineui',
  'Rewind': 'rewind',
  'Rhombus': 'rhombus',
  'Ribbon': 'ribbon',
  'Road': 'road',
  'Road cone': 'road-cone',
  'Rocket': 'rocket',
  'Rotation': 'rotation',
  'Router': 'router',
  'Rss': 'rss',
  'Ruler': 'ruler',
  'Run': 'run',
  'Save': 'save',
  'Scales': 'scales',
  'Script': 'script',
  'Search': 'search',
  'Send': 'send',
  'Serial port': 'serial-port',
  'Server': 'server',
  'Server link': 'server-link',
  'Server play': 'server-play',
  'Service bell': 'service-bell',
  'Settings': 'settings',
  'Shape exclude': 'shape-exclude',
  'Shape intersect': 'shape-intersect',
  'Shape subtract': 'shape-subtract',
  'Shape union': 'shape-union',
  'Shapes': 'shapes',
  'Share': 'share',
  'Share android': 'share-android',
  'Share ios': 'share-ios',
  'Shell script': 'shell-script',
  'Shield': 'shield',
  'Shopping bag': 'shopping-bag',
  'Sim': 'sim',
  'Slide add': 'slide-add',
  'Slide content': 'slide-content',
  'Slide eraser': 'slide-eraser',
  'Slide grid': 'slide-grid',
  'Slide hide': 'slide-hide',
  'Slide layout': 'slide-layout',
  'Smartwatch': 'smartwatch',
  'Sound source': 'sound-source',
  'Spacebar': 'spacebar',
  'Sport baseball': 'sport-baseball',
  'Sport basketball': 'sport-basketball',
  'Sport soccer': 'sport-soccer',
  'Spray can': 'spray-can',
  'Square': 'square',
  'Square hint': 'square-hint',
  'Square multiple': 'square-multiple',
  'Star': 'star',
  'Stop': 'stop',
  'Subtract': 'subtract',
  'Swift': 'swift',
  'Tab': 'tab',
  'Tablet': 'tablet',
  'Tag': 'tag',
  'Target': 'target',
  'Temperature': 'temperature',
  'Tent': 'tent',
  'Text': 'text',
  'Text align center': 'text-align-center',
  'Text align justify': 'text-align-justify',
  'Text align left': 'text-align-left',
  'Text align right': 'text-align-right',
  'Textbox': 'textbox',
  'Textbox align bottom': 'textbox-align-bottom',
  'Textbox align bottom center': 'textbox-align-bottom-center',
  'Textbox align bottom left': 'textbox-align-bottom-left',
  'Textbox align bottom right': 'textbox-align-bottom-right',
  'Textbox align center': 'textbox-align-center',
  'Textbox align middle': 'textbox-align-middle',
  'Textbox align middle left': 'textbox-align-middle-left',
  'Textbox align middle right': 'textbox-align-middle-right',
  'Textbox align top': 'textbox-align-top',
  'Textbox align top center': 'textbox-align-top-center',
  'Textbox align top left': 'textbox-align-top-left',
  'Textbox align top right': 'textbox-align-top-right',
  'Thinking': 'thinking',
  'Ticket': 'ticket',
  'Timer': 'timer',
  'Toggle left': 'toggle-left',
  'Toggle multiple': 'toggle-multiple',
  'Toggle right': 'toggle-right',
  'Toolbox': 'toolbox',
  'Trophy': 'trophy',
  'Tv': 'tv',
  'Typescript': 'typescript',
  'Umbrella': 'umbrella',
  'Usb': 'usb',
  'Usb cable': 'usb-cable',
  'Verified': 'verified',
  'Video': 'video',
  'Video clip': 'video-clip',
  'Video play pause': 'video-play-pause',
  'Voicemail': 'voicemail',
  'Vote': 'vote',
  'Walkie talkie': 'walkie-talkie',
  'Wallet': 'wallet',
  'Wand': 'wand',
  'Warning': 'warning',
  'Washer': 'washer',
  'Water': 'water',
  'Weather blowing snow': 'weather-blowing-snow',
  'Weather cloudy': 'weather-cloudy',
  'Weather rain': 'weather-rain',
  'Weather snow': 'weather-snow',
  'Weather snowflake': 'weather-snowflake',
  'Weather sunny': 'weather-sunny',
  'Weather thunderstorm': 'weather-thunderstorm',
  'Web': 'web',
  'Wifi 1': 'wifi-1',
  'Wifi 2': 'wifi-2',
  'Wifi 3': 'wifi-3',
  'Wifi 4': 'wifi-4',
  'Windows': 'windows',
  'Wrench': 'wrench',
  'Xray': 'xray',
  'Zoom': 'zoom',
  'Zoom in': 'zoom-in',
  'Zoom out': 'zoom_out'
};
