/**
 * RefineUI System Icons CDN Package Constants
 * 
 * This file contains all the configuration constants and icon metadata
 * used throughout the CDN package.
 */

import { CDNConfig, BuildConfig } from './types';

/** CDN configuration for the package */
export const CDN_CONFIG: CDNConfig = {
  packageName: '@refineui/icon-cdn',
  version: '1.0.0',
  baseUrl: 'https://cdn.jsdelivr.net/npm'
};

/** Build configuration for generating icon files */
export const BUILD_CONFIG: BuildConfig = {
  sourceDir: '../../assets',
  outputDir: './icons',
  sizes: [16, 20, 24, 28, 32, 48],
  styles: ['regular', 'filled']
};

/** Complete icon metadata with all available icons */
export const ICON_METADATA = {
  sizes: [16, 20, 24, 28, 32, 48] as const,
  styles: ['regular', 'filled'] as const,
  icons: [
    'access_time', 'accessibility', 'add', 'add_circle', 'add_square', 'airplane',
    'album', 'alert', 'alert_badge', 'alert_off', 'align_bottom', 'align_center_horizontal',
    'align_center_vertical', 'align_left', 'align_right', 'align_top', 'android',
    'app_folder', 'app_recent', 'app_title', 'appstore', 'autosum', 'backpack',
    'backspace', 'badge', 'balloon', 'bar_chart_horizontal', 'bar_chart_horizontal_descending',
    'bar_chart_vertical', 'bar_chart_vertical_descending', 'barcode_scanner', 'battery_0',
    'battery_10', 'battery_100', 'battery_20', 'battery_30', 'battery_40', 'battery_50',
    'battery_60', 'battery_70', 'battery_80', 'battery_90', 'block', 'bluetooth',
    'blur', 'board', 'book', 'bookmark', 'bug', 'calculator', 'calendar', 'camera',
    'cart', 'carton_box', 'chart', 'chat', 'chat_add', 'chat_empty', 'checkmark',
    'chess', 'chevron_down', 'chevron_left', 'chevron_right', 'chevron_up', 'circle',
    'clipboard', 'clock', 'clock_alarm', 'cloud', 'clover', 'code', 'code_block',
    'comma', 'comment', 'cone', 'contrast', 'control_button', 'cookie', 'copy',
    'couch', 'cpu', 'crop', 'crown', 'css', 'cube', 'cursor', 'cut', 'dart',
    'database', 'delete', 'delete_off', 'dentist', 'desk', 'desktop', 'desktop_mac',
    'dialpad', 'diamond', 'dismiss', 'dismiss_circle', 'dismiss_square', 'doctor',
    'document', 'document_border', 'door', 'drag', 'drawer', 'drop', 'dual_screen',
    'dumbbell', 'dust', 'earth', 'edit', 'edit_off', 'elevator', 'emoji',
    'emoji_angry', 'emoji_cool', 'emoji_grimacing', 'emoji_laugh', 'emoji_meh',
    'emoji_sad', 'emoji_surprise', 'engine', 'equal', 'equal_circle', 'equal_off',
    'error_circle', 'eye', 'eye_off', 'eyedropper', 'eyedropper_off', 'fast_forward',
    'filmstrip', 'filmstrip_off', 'filter', 'fire', 'flag', 'flag_off', 'flash',
    'flash_off', 'flashlight', 'flashlight_off', 'flip_horizontal', 'flip_vertcial',
    'folder', 'folder_open', 'frame', 'full_screen_maximize', 'full_screen_minimize',
    'games', 'gantt_chart', 'gas', 'gas_station', 'gavel', 'gif', 'gift', 'gift_card',
    'git', 'glasses', 'global', 'grid', 'guest', 'guitar', 'hammer', 'hard_drive',
    'hat_graduation', 'hd', 'hdr', 'hdr_off', 'headphones', 'headphones_mic', 'headset_vr',
    'heart', 'heart_broken', 'hexagon', 'highlight', 'highway', 'home', 'home_checkmark',
    'hourglass', 'hourglass_half', 'hourglass_one_quarter', 'hourglass_three_quarter',
    'html', 'image', 'image_circle', 'important', 'incognito', 'info', 'ios',
    'ios_arrow_ltr', 'ios_arrow_rtl', 'ios_chevron_ltr', 'ios_chevron_rtl', 'iot',
    'javascript', 'joystick', 'json', 'json_file', 'key', 'key_multiple', 'keyboard',
    'keyboard_backspace', 'keyboard_command', 'keyboard_lock', 'keyboard_off',
    'keyboard_option', 'keyboard_return', 'keyboard_shift', 'keyboard_shift_uppercase',
    'keyboard_tab', 'kiosk', 'kotlin', 'laptop', 'layer', 'lightbulb', 'line',
    'line_dashes', 'line_horizontal_1', 'line_horizontal_1_dashes', 'link', 'location',
    'location_arrow', 'lock_closed', 'lock_open', 'luggage', 'macos', 'mail',
    'mail_read', 'mailbox', 'map', 'markdown', 'math_symbols', 'megaphone', 'mic',
    'moon', 'more_circle', 'more_horizontal', 'more_vertcial', 'mouse', 'movie',
    'network_check', 'news', 'next', 'note', 'notebook', 'notepad', 'number_circle_0',
    'number_circle_1', 'number_circle_2', 'number_circle_3', 'number_circle_4',
    'number_circle_5', 'number_circle_6', 'number_circle_7', 'number_circle_8',
    'number_circle_9', 'number_symbol', 'number_symbol_circle', 'number_symbol_square',
    'opacity', 'open', 'open_off', 'options', 'organization', 'organization_horizontal',
    'orientation', 'oval', 'oven', 'padding', 'page_fit', 'paint_brush', 'paint_bucket',
    'parallelogram', 'password', 'pause', 'pause_circle', 'payment', 'payment_wireless',
    'pen', 'pen_off', 'pentagon', 'person', 'person_voice', 'phone', 'piano', 'pin',
    'pipeline', 'play', 'play_circle', 'playstore', 'port_hdmi', 'port_micro_usb',
    'port_usb_a', 'port_usb_c', 'power', 'preview_link', 'previous', 'print',
    'pulse', 'pulse_circle', 'pulse_square', 'python', 'qr_code', 'question',
    'question_circle', 'radio_button', 'ram', 'record', 'record_stop', 'rectangle',
    'refineui', 'rewind', 'rhombus', 'ribbon', 'road', 'road_cone', 'rocket',
    'rotation', 'router', 'rss', 'ruler', 'run', 'save', 'scales', 'script',
    'search', 'send', 'serial_port', 'server', 'server_link', 'server_play',
    'service_bell', 'settings', 'shape_exclude', 'shape_intersect', 'shape_subtract',
    'shape_union', 'shapes', 'share', 'share_android', 'share_ios', 'shell_script',
    'shield', 'shopping_bag', 'sim', 'slide_add', 'slide_content', 'slide_eraser',
    'slide_grid', 'slide_hide', 'slide_layout', 'smartwatch', 'sound_source',
    'spacebar', 'sport_baseball', 'sport_basketball', 'sport_soccer', 'spray_can',
    'square', 'square_hint', 'square_multiple', 'star', 'stop', 'subtract',
    'swift', 'tab', 'tablet', 'tag', 'target', 'temperature', 'tent', 'text',
    'text_align_center', 'text_align_justify', 'text_align_left', 'text_align_right',
    'textbox', 'textbox_align_bottom', 'textbox_align_bottom_center',
    'textbox_align_bottom_left', 'textbox_align_bottom_right', 'textbox_align_center',
    'textbox_align_middle', 'textbox_align_middle_left', 'textbox_align_middle_right',
    'textbox_align_top', 'textbox_align_top_center', 'textbox_align_top_left',
    'textbox_align_top_right', 'thinking', 'ticket', 'timer', 'toggle_left',
    'toggle_multiple', 'toggle_right', 'toolbox', 'trophy', 'tv', 'typescript',
    'umbrella', 'usb', 'usb_cable', 'verified', 'video', 'video_clip',
    'video_play_pause', 'voicemail', 'vote', 'walkie_talkie', 'wallet', 'wand',
    'warning', 'washer', 'water', 'weather_blowing_snow', 'weather_cloudy',
    'weather_rain', 'weather_snow', 'weather_snowflake', 'weather_sunny',
    'weather_thunderstorm', 'web', 'wifi_1', 'wifi_2', 'wifi_3', 'wifi_4',
    'windows', 'wrench', 'xray', 'zoom', 'zoom_in', 'zoom_out'
  ]
} as const;

/** Icon name mapping from display names to snake_case format */
export const ICON_NAME_MAPPING: Record<string, string> = {
  'Access time': 'access_time',
  'Accessibility': 'accessibility',
  'Add': 'add',
  'Add circle': 'add_circle',
  'Add square': 'add_square',
  'Airplane': 'airplane',
  'Album': 'album',
  'Alert': 'alert',
  'Alert badge': 'alert_badge',
  'Alert off': 'alert_off',
  'Align bottom': 'align_bottom',
  'Align center horizontal': 'align_center_horizontal',
  'Align center vertical': 'align_center_vertical',
  'Align left': 'align_left',
  'Align right': 'align_right',
  'Align top': 'align_top',
  'Android': 'android',
  'App folder': 'app_folder',
  'App recent': 'app_recent',
  'App title': 'app_title',
  'Appstore': 'appstore',
  'Autosum': 'autosum',
  'Backpack': 'backpack',
  'Backspace': 'backspace',
  'Badge': 'badge',
  'Balloon': 'balloon',
  'Bar chart horizontal': 'bar_chart_horizontal',
  'Bar chart horizontal descending': 'bar_chart_horizontal_descending',
  'Bar chart vertical': 'bar_chart_vertical',
  'Bar chart vertical descending': 'bar_chart_vertical_descending',
  'Barcode scanner': 'barcode_scanner',
  'Battery 0': 'battery_0',
  'Battery 10': 'battery_10',
  'Battery 100': 'battery_100',
  'Battery 20': 'battery_20',
  'Battery 30': 'battery_30',
  'Battery 40': 'battery_40',
  'Battery 50': 'battery_50',
  'Battery 60': 'battery_60',
  'Battery 70': 'battery_70',
  'Battery 80': 'battery_80',
  'Battery 90': 'battery_90',
  'Block': 'block',
  'Bluetooth': 'bluetooth',
  'Blur': 'blur',
  'Board': 'board',
  'Book': 'book',
  'Bookmark': 'bookmark',
  'Bug': 'bug',
  'Calculator': 'calculator',
  'Calendar': 'calendar',
  'Camera': 'camera',
  'Cart': 'cart',
  'Carton box': 'carton_box',
  'Chart': 'chart',
  'Chat': 'chat',
  'Chat add': 'chat_add',
  'Chat empty': 'chat_empty',
  'Checkmark': 'checkmark',
  'Chess': 'chess',
  'Chevron down': 'chevron_down',
  'Chevron left': 'chevron_left',
  'Chevron right': 'chevron_right',
  'Chevron up': 'chevron_up',
  'Circle': 'circle',
  'Clipboard': 'clipboard',
  'Clock': 'clock',
  'Clock alarm': 'clock_alarm',
  'Cloud': 'cloud',
  'Clover': 'clover',
  'Code': 'code',
  'Code block': 'code_block',
  'Comma': 'comma',
  'Comment': 'comment',
  'Cone': 'cone',
  'Contrast': 'contrast',
  'Control button': 'control_button',
  'Cookie': 'cookie',
  'Copy': 'copy',
  'Couch': 'couch',
  'Cpu': 'cpu',
  'Crop': 'crop',
  'Crown': 'crown',
  'Css': 'css',
  'Cube': 'cube',
  'Cursor': 'cursor',
  'Cut': 'cut',
  'Dart': 'dart',
  'Database': 'database',
  'Delete': 'delete',
  'Delete off': 'delete_off',
  'Dentist': 'dentist',
  'Desk': 'desk',
  'Desktop': 'desktop',
  'Desktop mac': 'desktop_mac',
  'Dialpad': 'dialpad',
  'Diamond': 'diamond',
  'Dismiss': 'dismiss',
  'Dismiss circle': 'dismiss_circle',
  'Dismiss square': 'dismiss_square',
  'Doctor': 'doctor',
  'Document': 'document',
  'Document border': 'document_border',
  'Door': 'door',
  'Drag': 'drag',
  'Drawer': 'drawer',
  'Drop': 'drop',
  'Dual screen': 'dual_screen',
  'Dumbbell': 'dumbbell',
  'Dust': 'dust',
  'Earth': 'earth',
  'Edit': 'edit',
  'Edit off': 'edit_off',
  'Elevator': 'elevator',
  'Emoji': 'emoji',
  'Emoji angry': 'emoji_angry',
  'Emoji cool': 'emoji_cool',
  'Emoji grimacing': 'emoji_grimacing',
  'Emoji laugh': 'emoji_laugh',
  'Emoji meh': 'emoji_meh',
  'Emoji sad': 'emoji_sad',
  'Emoji surprise': 'emoji_surprise',
  'Engine': 'engine',
  'Equal': 'equal',
  'Equal circle': 'equal_circle',
  'Equal off': 'equal_off',
  'Error circle': 'error_circle',
  'Eye': 'eye',
  'Eye off': 'eye_off',
  'Eyedropper': 'eyedropper',
  'Eyedropper off': 'eyedropper_off',
  'Fast forward': 'fast_forward',
  'Filmstrip': 'filmstrip',
  'Filmstrip off': 'filmstrip_off',
  'Filter': 'filter',
  'Fire': 'fire',
  'Flag': 'flag',
  'Flag off': 'flag_off',
  'Flash': 'flash',
  'Flash off': 'flash_off',
  'Flashlight': 'flashlight',
  'Flashlight off': 'flashlight_off',
  'Flip horizontal': 'flip_horizontal',
  'Flip verticial': 'flip_vertcial',
  'Folder': 'folder',
  'Folder open': 'folder_open',
  'Frame': 'frame',
  'Full screen maximize': 'full_screen_maximize',
  'Full screen minimize': 'full_screen_minimize',
  'Games': 'games',
  'Gantt chart': 'gantt_chart',
  'Gas': 'gas',
  'Gas station': 'gas_station',
  'Gavel': 'gavel',
  'Gif': 'gif',
  'Gift': 'gift',
  'Gift card': 'gift_card',
  'Git': 'git',
  'Glasses': 'glasses',
  'Global': 'global',
  'Grid': 'grid',
  'Guest': 'guest',
  'Guitar': 'guitar',
  'Hammer': 'hammer',
  'Hard drive': 'hard_drive',
  'Hat graduation': 'hat_graduation',
  'Hd': 'hd',
  'Hdr': 'hdr',
  'Hdr off': 'hdr_off',
  'Headphones': 'headphones',
  'Headphones mic': 'headphones_mic',
  'Headset vr': 'headset_vr',
  'Heart': 'heart',
  'Heart broken': 'heart_broken',
  'Hexagon': 'hexagon',
  'Highlight': 'highlight',
  'Highway': 'highway',
  'Home': 'home',
  'Home checkmark': 'home_checkmark',
  'Hourglass': 'hourglass',
  'Hourglass half': 'hourglass_half',
  'Hourglass one quarter': 'hourglass_one_quarter',
  'Hourglass three quarter': 'hourglass_three_quarter',
  'Html': 'html',
  'Image': 'image',
  'Image circle': 'image_circle',
  'Important': 'important',
  'Incognito': 'incognito',
  'Info': 'info',
  'Ios': 'ios',
  'Ios arrow ltr': 'ios_arrow_ltr',
  'Ios arrow rtl': 'ios_arrow_rtl',
  'Ios chevron ltr': 'ios_chevron_ltr',
  'Ios chevron rtl': 'ios_chevron_rtl',
  'Iot': 'iot',
  'Javascript': 'javascript',
  'Joystick': 'joystick',
  'Json': 'json',
  'Json file': 'json_file',
  'Key': 'key',
  'Key multiple': 'key_multiple',
  'Keyboard': 'keyboard',
  'Keyboard backspace': 'keyboard_backspace',
  'Keyboard command': 'keyboard_command',
  'Keyboard lock': 'keyboard_lock',
  'Keyboard off': 'keyboard_off',
  'Keyboard option': 'keyboard_option',
  'Keyboard return': 'keyboard_return',
  'Keyboard shift': 'keyboard_shift',
  'Keyboard shift uppercase': 'keyboard_shift_uppercase',
  'Keyboard tab': 'keyboard_tab',
  'Kiosk': 'kiosk',
  'Kotlin': 'kotlin',
  'Laptop': 'laptop',
  'Layer': 'layer',
  'Lightbulb': 'lightbulb',
  'Line': 'line',
  'Line dashes': 'line_dashes',
  'Line horizontal 1': 'line_horizontal_1',
  'Line horizontal 1 dashes': 'line_horizontal_1_dashes',
  'Link': 'link',
  'Location': 'location',
  'Location arrow': 'location_arrow',
  'Lock closed': 'lock_closed',
  'Lock open': 'lock_open',
  'Luggage': 'luggage',
  'Macos': 'macos',
  'Mail': 'mail',
  'Mail read': 'mail_read',
  'Mailbox': 'mailbox',
  'Map': 'map',
  'Markdown': 'markdown',
  'Math symbols': 'math_symbols',
  'Megaphone': 'megaphone',
  'Mic': 'mic',
  'Moon': 'moon',
  'More circle': 'more_circle',
  'More horizontal': 'more_horizontal',
  'More verticial': 'more_vertcial',
  'Mouse': 'mouse',
  'Movie': 'movie',
  'Network check': 'network_check',
  'News': 'news',
  'Next': 'next',
  'Note': 'note',
  'Notebook': 'notebook',
  'Notepad': 'notepad',
  'Number circle 0': 'number_circle_0',
  'Number circle 1': 'number_circle_1',
  'Number circle 2': 'number_circle_2',
  'Number circle 3': 'number_circle_3',
  'Number circle 4': 'number_circle_4',
  'Number circle 5': 'number_circle_5',
  'Number circle 6': 'number_circle_6',
  'Number circle 7': 'number_circle_7',
  'Number circle 8': 'number_circle_8',
  'Number circle 9': 'number_circle_9',
  'Number symbol': 'number_symbol',
  'Number symbol circle': 'number_symbol_circle',
  'Number symbol square': 'number_symbol_square',
  'Opacity': 'opacity',
  'Open': 'open',
  'Open off': 'open_off',
  'Options': 'options',
  'Organization': 'organization',
  'Organization horizontal': 'organization_horizontal',
  'Orientation': 'orientation',
  'Oval': 'oval',
  'Oven': 'oven',
  'Padding': 'padding',
  'Page fit': 'page_fit',
  'Paint brush': 'paint_brush',
  'Paint bucket': 'paint_bucket',
  'Parallelogram': 'parallelogram',
  'Password': 'password',
  'Pause': 'pause',
  'Pause circle': 'pause_circle',
  'Payment': 'payment',
  'Payment wireless': 'payment_wireless',
  'Pen': 'pen',
  'Pen off': 'pen_off',
  'Pentagon': 'pentagon',
  'Person': 'person',
  'Person voice': 'person_voice',
  'Phone': 'phone',
  'Piano': 'piano',
  'Pin': 'pin',
  'Pipeline': 'pipeline',
  'Play': 'play',
  'Play circle': 'play_circle',
  'Playstore': 'playstore',
  'Port hdmi': 'port_hdmi',
  'Port micro usb': 'port_micro_usb',
  'Port usb a': 'port_usb_a',
  'Port usb c': 'port_usb_c',
  'Power': 'power',
  'Preview link': 'preview_link',
  'Previous': 'previous',
  'Print': 'print',
  'Pulse': 'pulse',
  'Pulse circle': 'pulse_circle',
  'Pulse square': 'pulse_square',
  'Python': 'python',
  'Qr code': 'qr_code',
  'Question': 'question',
  'Question circle': 'question_circle',
  'Radio button': 'radio_button',
  'Ram': 'ram',
  'Record': 'record',
  'Record stop': 'record_stop',
  'Rectangle': 'rectangle',
  'Refineui': 'refineui',
  'Rewind': 'rewind',
  'Rhombus': 'rhombus',
  'Ribbon': 'ribbon',
  'Road': 'road',
  'Road cone': 'road_cone',
  'Rocket': 'rocket',
  'Rotation': 'rotation',
  'Router': 'router',
  'Rss': 'rss',
  'Ruler': 'ruler',
  'Run': 'run',
  'Save': 'save',
  'Scales': 'scales',
  'Script': 'script',
  'Search': 'search',
  'Send': 'send',
  'Serial port': 'serial_port',
  'Server': 'server',
  'Server link': 'server_link',
  'Server play': 'server_play',
  'Service bell': 'service_bell',
  'Settings': 'settings',
  'Shape exclude': 'shape_exclude',
  'Shape intersect': 'shape_intersect',
  'Shape subtract': 'shape_subtract',
  'Shape union': 'shape_union',
  'Shapes': 'shapes',
  'Share': 'share',
  'Share android': 'share_android',
  'Share ios': 'share_ios',
  'Shell script': 'shell_script',
  'Shield': 'shield',
  'Shopping bag': 'shopping_bag',
  'Sim': 'sim',
  'Slide add': 'slide_add',
  'Slide content': 'slide_content',
  'Slide eraser': 'slide_eraser',
  'Slide grid': 'slide_grid',
  'Slide hide': 'slide_hide',
  'Slide layout': 'slide_layout',
  'Smartwatch': 'smartwatch',
  'Sound source': 'sound_source',
  'Spacebar': 'spacebar',
  'Sport baseball': 'sport_baseball',
  'Sport basketball': 'sport_basketball',
  'Sport soccer': 'sport_soccer',
  'Spray can': 'spray_can',
  'Square': 'square',
  'Square hint': 'square_hint',
  'Square multiple': 'square_multiple',
  'Star': 'star',
  'Stop': 'stop',
  'Subtract': 'subtract',
  'Swift': 'swift',
  'Tab': 'tab',
  'Tablet': 'tablet',
  'Tag': 'tag',
  'Target': 'target',
  'Temperature': 'temperature',
  'Tent': 'tent',
  'Text': 'text',
  'Text align center': 'text_align_center',
  'Text align justify': 'text_align_justify',
  'Text align left': 'text_align_left',
  'Text align right': 'text_align_right',
  'Textbox': 'textbox',
  'Textbox align bottom': 'textbox_align_bottom',
  'Textbox align bottom center': 'textbox_align_bottom_center',
  'Textbox align bottom left': 'textbox_align_bottom_left',
  'Textbox align bottom right': 'textbox_align_bottom_right',
  'Textbox align center': 'textbox_align_center',
  'Textbox align middle': 'textbox_align_middle',
  'Textbox align middle left': 'textbox_align_middle_left',
  'Textbox align middle right': 'textbox_align_middle_right',
  'Textbox align top': 'textbox_align_top',
  'Textbox align top center': 'textbox_align_top_center',
  'Textbox align top left': 'textbox_align_top_left',
  'Textbox align top right': 'textbox_align_top_right',
  'Thinking': 'thinking',
  'Ticket': 'ticket',
  'Timer': 'timer',
  'Toggle left': 'toggle_left',
  'Toggle multiple': 'toggle_multiple',
  'Toggle right': 'toggle_right',
  'Toolbox': 'toolbox',
  'Trophy': 'trophy',
  'Tv': 'tv',
  'Typescript': 'typescript',
  'Umbrella': 'umbrella',
  'Usb': 'usb',
  'Usb cable': 'usb_cable',
  'Verified': 'verified',
  'Video': 'video',
  'Video clip': 'video_clip',
  'Video play pause': 'video_play_pause',
  'Voicemail': 'voicemail',
  'Vote': 'vote',
  'Walkie talkie': 'walkie_talkie',
  'Wallet': 'wallet',
  'Wand': 'wand',
  'Warning': 'warning',
  'Washer': 'washer',
  'Water': 'water',
  'Weather blowing snow': 'weather_blowing_snow',
  'Weather cloudy': 'weather_cloudy',
  'Weather rain': 'weather_rain',
  'Weather snow': 'weather_snow',
  'Weather snowflake': 'weather_snowflake',
  'Weather sunny': 'weather_sunny',
  'Weather thunderstorm': 'weather_thunderstorm',
  'Web': 'web',
  'Wifi 1': 'wifi_1',
  'Wifi 2': 'wifi_2',
  'Wifi 3': 'wifi_3',
  'Wifi 4': 'wifi_4',
  'Windows': 'windows',
  'Wrench': 'wrench',
  'Xray': 'xray',
  'Zoom': 'zoom',
  'Zoom in': 'zoom_in',
  'Zoom out': 'zoom_out'
};
