/**
 * RefineUI System Icons Web Package Constants
 */

import { IconSize, IconStyle } from './types';

/** Available icon sizes */
export const ICON_SIZES: IconSize[] = [16, 20, 24, 28, 32, 48];

/** Available icon styles */
export const ICON_STYLES: IconStyle[] = ['regular', 'filled'];

/** Base URL for icon assets */
export const ICON_BASE_URL = '/icons';

/** API endpoint for icon metadata */
export const ICON_API_URL = '/api/icons';

/** Default icon size */
export const DEFAULT_ICON_SIZE: IconSize = 24;

/** Default icon style */
export const DEFAULT_ICON_STYLE: IconStyle = 'regular';

/** Icon categories for organization */
export const ICON_CATEGORIES = {
  /** Navigation icons */
  navigation: ['home', 'search', 'arrow', 'chevron', 'location', 'map'],
  /** Action icons */
  actions: ['add', 'edit', 'delete', 'save', 'close', 'checkmark'],
  /** Communication icons */
  communication: ['mail', 'chat', 'phone', 'share', 'notification'],
  /** Media icons */
  media: ['play', 'pause', 'stop', 'video', 'audio', 'camera'],
  /** Social icons */
  social: ['person', 'user', 'group', 'heart', 'star'],
  /** Technology icons */
  technology: ['computer', 'laptop', 'phone', 'tablet', 'wifi'],
  /** Weather icons */
  weather: ['sun', 'moon', 'cloud', 'rain', 'snow'],
  /** Tools icons */
  tools: ['settings', 'gear', 'tool', 'wrench', 'hammer']
} as const;

/** Icon name mapping for display */
export const ICON_NAME_MAPPING: Record<string, string> = {
  'access_time': 'Access Time',
  'accessibility': 'Accessibility',
  'add': 'Add',
  'add_circle': 'Add Circle',
  'add_square': 'Add Square',
  'airplane': 'Airplane',
  'album': 'Album',
  'alert': 'Alert',
  'alert_badge': 'Alert Badge',
  'alert_off': 'Alert Off',
  'align_bottom': 'Align Bottom',
  'align_center_horizontal': 'Align Center Horizontal',
  'align_center_vertical': 'Align Center Vertical',
  'align_left': 'Align Left',
  'align_right': 'Align Right',
  'align_top': 'Align Top',
  'android': 'Android',
  'app_folder': 'App Folder',
  'app_recent': 'App Recent',
  'app_title': 'App Title',
  'appstore': 'App Store',
  'autosum': 'Autosum',
  'backpack': 'Backpack',
  'backspace': 'Backspace',
  'badge': 'Badge',
  'balloon': 'Balloon',
  'bar_chart_horizontal': 'Bar Chart Horizontal',
  'bar_chart_horizontal_descending': 'Bar Chart Horizontal Descending',
  'bar_chart_vertical': 'Bar Chart Vertical',
  'bar_chart_vertical_descending': 'Bar Chart Vertical Descending',
  'barcode_scanner': 'Barcode Scanner',
  'battery_0': 'Battery 0%',
  'battery_10': 'Battery 10%',
  'battery_100': 'Battery 100%',
  'battery_20': 'Battery 20%',
  'battery_30': 'Battery 30%',
  'battery_40': 'Battery 40%',
  'battery_50': 'Battery 50%',
  'battery_60': 'Battery 60%',
  'battery_70': 'Battery 70%',
  'battery_80': 'Battery 80%',
  'battery_90': 'Battery 90%',
  'block': 'Block',
  'bluetooth': 'Bluetooth',
  'blur': 'Blur',
  'board': 'Board',
  'book': 'Book',
  'bookmark': 'Bookmark',
  'bug': 'Bug',
  'calculator': 'Calculator',
  'calendar': 'Calendar',
  'camera': 'Camera',
  'cart': 'Cart',
  'carton_box': 'Carton Box',
  'chart': 'Chart',
  'chat': 'Chat',
  'chat_add': 'Chat Add',
  'chat_empty': 'Chat Empty',
  'checkmark': 'Checkmark',
  'chess': 'Chess',
  'chevron_down': 'Chevron Down',
  'chevron_left': 'Chevron Left',
  'chevron_right': 'Chevron Right',
  'chevron_up': 'Chevron Up',
  'circle': 'Circle',
  'clipboard': 'Clipboard',
  'clock': 'Clock',
  'clock_alarm': 'Clock Alarm',
  'cloud': 'Cloud',
  'clover': 'Clover',
  'code': 'Code',
  'code_block': 'Code Block',
  'comma': 'Comma',
  'comment': 'Comment',
  'cone': 'Cone',
  'contrast': 'Contrast',
  'control_button': 'Control Button',
  'cookie': 'Cookie',
  'copy': 'Copy',
  'couch': 'Couch',
  'cpu': 'CPU',
  'crop': 'Crop',
  'crown': 'Crown',
  'css': 'CSS',
  'cube': 'Cube',
  'cursor': 'Cursor',
  'cut': 'Cut',
  'dart': 'Dart',
  'database': 'Database',
  'delete': 'Delete',
  'delete_off': 'Delete Off',
  'dentist': 'Dentist',
  'desk': 'Desk',
  'desktop': 'Desktop',
  'desktop_mac': 'Desktop Mac',
  'dialpad': 'Dialpad',
  'diamond': 'Diamond',
  'dismiss': 'Dismiss',
  'dismiss_circle': 'Dismiss Circle',
  'dismiss_square': 'Dismiss Square',
  'doctor': 'Doctor',
  'document': 'Document',
  'document_border': 'Document Border',
  'door': 'Door',
  'drag': 'Drag',
  'drawer': 'Drawer',
  'drop': 'Drop',
  'dual_screen': 'Dual Screen',
  'dumbbell': 'Dumbbell',
  'dust': 'Dust',
  'earth': 'Earth',
  'edit': 'Edit',
  'edit_off': 'Edit Off',
  'elevator': 'Elevator',
  'emoji': 'Emoji',
  'emoji_angry': 'Emoji Angry',
  'emoji_cool': 'Emoji Cool',
  'emoji_grimacing': 'Emoji Grimacing',
  'emoji_laugh': 'Emoji Laugh',
  'emoji_meh': 'Emoji Meh',
  'emoji_sad': 'Emoji Sad',
  'emoji_surprise': 'Emoji Surprise',
  'engine': 'Engine',
  'equal': 'Equal',
  'equal_circle': 'Equal Circle',
  'equal_off': 'Equal Off',
  'error_circle': 'Error Circle',
  'eye': 'Eye',
  'eye_off': 'Eye Off',
  'eyedropper': 'Eyedropper',
  'eyedropper_off': 'Eyedropper Off',
  'fast_forward': 'Fast Forward',
  'filmstrip': 'Filmstrip',
  'filmstrip_off': 'Filmstrip Off',
  'filter': 'Filter',
  'fire': 'Fire',
  'flag': 'Flag',
  'flag_off': 'Flag Off',
  'flash': 'Flash',
  'flash_off': 'Flash Off',
  'flashlight': 'Flashlight',
  'flashlight_off': 'Flashlight Off',
  'flip_horizontal': 'Flip Horizontal',
  'flip_vertcial': 'Flip Vertical',
  'folder': 'Folder',
  'folder_open': 'Folder Open',
  'frame': 'Frame',
  'full_screen_maximize': 'Full Screen Maximize',
  'full_screen_minimize': 'Full Screen Minimize',
  'games': 'Games',
  'gantt_chart': 'Gantt Chart',
  'gas': 'Gas',
  'gas_station': 'Gas Station',
  'gavel': 'Gavel',
  'gif': 'GIF',
  'gift': 'Gift',
  'gift_card': 'Gift Card',
  'git': 'Git',
  'glasses': 'Glasses',
  'global': 'Global',
  'grid': 'Grid',
  'guest': 'Guest',
  'guitar': 'Guitar',
  'hammer': 'Hammer',
  'hard_drive': 'Hard Drive',
  'hat_graduation': 'Graduation Hat',
  'hd': 'HD',
  'hdr': 'HDR',
  'hdr_off': 'HDR Off',
  'headphones': 'Headphones',
  'headphones_mic': 'Headphones with Mic',
  'headset_vr': 'VR Headset',
  'heart': 'Heart',
  'heart_broken': 'Broken Heart',
  'hexagon': 'Hexagon',
  'highlight': 'Highlight',
  'highway': 'Highway',
  'home': 'Home',
  'home_checkmark': 'Home Checkmark',
  'hourglass': 'Hourglass',
  'hourglass_half': 'Hourglass Half',
  'hourglass_one_quarter': 'Hourglass One Quarter',
  'hourglass_three_quarter': 'Hourglass Three Quarter',
  'html': 'HTML',
  'image': 'Image',
  'image_circle': 'Circular Image',
  'important': 'Important',
  'incognito': 'Incognito',
  'info': 'Info',
  'ios': 'iOS',
  'ios_arrow_ltr': 'iOS Arrow LTR',
  'ios_arrow_rtl': 'iOS Arrow RTL',
  'ios_chevron_ltr': 'iOS Chevron LTR',
  'ios_chevron_rtl': 'iOS Chevron RTL',
  'iot': 'IoT',
  'javascript': 'JavaScript',
  'joystick': 'Joystick',
  'json': 'JSON',
  'json_file': 'JSON File',
  'key': 'Key',
  'key_multiple': 'Multiple Keys',
  'keyboard': 'Keyboard',
  'keyboard_backspace': 'Keyboard Backspace',
  'keyboard_command': 'Keyboard Command',
  'keyboard_lock': 'Keyboard Lock',
  'keyboard_off': 'Keyboard Off',
  'keyboard_option': 'Keyboard Option',
  'keyboard_return': 'Keyboard Return',
  'keyboard_shift': 'Keyboard Shift',
  'keyboard_shift_uppercase': 'Keyboard Shift Uppercase',
  'keyboard_tab': 'Keyboard Tab',
  'kiosk': 'Kiosk',
  'kotlin': 'Kotlin',
  'laptop': 'Laptop',
  'layer': 'Layer',
  'lightbulb': 'Lightbulb',
  'line': 'Line',
  'line_dashes': 'Dashed Line',
  'line_horizontal_1': 'Horizontal Line',
  'line_horizontal_1_dashes': 'Dashed Horizontal Line',
  'link': 'Link',
  'location': 'Location',
  'location_arrow': 'Location Arrow',
  'lock_closed': 'Lock Closed',
  'lock_open': 'Lock Open',
  'luggage': 'Luggage',
  'macos': 'macOS',
  'mail': 'Mail',
  'mail_read': 'Mail Read',
  'mailbox': 'Mailbox',
  'map': 'Map',
  'markdown': 'Markdown',
  'math_symbols': 'Math Symbols',
  'megaphone': 'Megaphone',
  'mic': 'Microphone',
  'moon': 'Moon',
  'more_circle': 'More Circle',
  'more_horizontal': 'More Horizontal',
  'more_vertcial': 'More Vertical',
  'mouse': 'Mouse',
  'movie': 'Movie',
  'network_check': 'Network Check',
  'news': 'News',
  'next': 'Next',
  'note': 'Note',
  'notebook': 'Notebook',
  'notepad': 'Notepad',
  'number_circle_0': 'Number Circle 0',
  'number_circle_1': 'Number Circle 1',
  'number_circle_2': 'Number Circle 2',
  'number_circle_3': 'Number Circle 3',
  'number_circle_4': 'Number Circle 4',
  'number_circle_5': 'Number Circle 5',
  'number_circle_6': 'Number Circle 6',
  'number_circle_7': 'Number Circle 7',
  'number_circle_8': 'Number Circle 8',
  'number_circle_9': 'Number Circle 9',
  'number_symbol': 'Number Symbol',
  'number_symbol_circle': 'Number Symbol Circle',
  'number_symbol_square': 'Number Symbol Square',
  'opacity': 'Opacity',
  'open': 'Open',
  'open_off': 'Open Off',
  'options': 'Options',
  'organization': 'Organization',
  'organization_horizontal': 'Organization Horizontal',
  'orientation': 'Orientation',
  'oval': 'Oval',
  'oven': 'Oven',
  'padding': 'Padding',
  'page_fit': 'Page Fit',
  'paint_brush': 'Paint Brush',
  'paint_bucket': 'Paint Bucket',
  'parallelogram': 'Parallelogram',
  'password': 'Password',
  'pause': 'Pause',
  'pause_circle': 'Pause Circle',
  'payment': 'Payment',
  'payment_wireless': 'Wireless Payment',
  'pen': 'Pen',
  'pen_off': 'Pen Off',
  'pentagon': 'Pentagon',
  'person': 'Person',
  'person_voice': 'Person Voice',
  'phone': 'Phone',
  'piano': 'Piano',
  'pin': 'Pin',
  'pipeline': 'Pipeline',
  'play': 'Play',
  'play_circle': 'Play Circle',
  'playstore': 'Play Store',
  'port_hdmi': 'HDMI Port',
  'port_micro_usb': 'Micro USB Port',
  'port_usb_a': 'USB A Port',
  'port_usb_c': 'USB C Port',
  'power': 'Power',
  'preview_link': 'Preview Link',
  'previous': 'Previous',
  'print': 'Print',
  'pulse': 'Pulse',
  'pulse_circle': 'Pulse Circle',
  'pulse_square': 'Pulse Square',
  'python': 'Python',
  'qr_code': 'QR Code',
  'question': 'Question',
  'question_circle': 'Question Circle',
  'radio_button': 'Radio Button',
  'ram': 'RAM',
  'record': 'Record',
  'record_stop': 'Record Stop',
  'rectangle': 'Rectangle',
  'refineui': 'RefineUI',
  'rewind': 'Rewind',
  'rhombus': 'Rhombus',
  'ribbon': 'Ribbon',
  'road': 'Road',
  'road_cone': 'Road Cone',
  'rocket': 'Rocket',
  'rotation': 'Rotation',
  'router': 'Router',
  'rss': 'RSS',
  'ruler': 'Ruler',
  'run': 'Run',
  'save': 'Save',
  'scales': 'Scales',
  'script': 'Script',
  'search': 'Search',
  'send': 'Send',
  'serial_port': 'Serial Port',
  'server': 'Server',
  'server_link': 'Server Link',
  'server_play': 'Server Play',
  'service_bell': 'Service Bell',
  'settings': 'Settings',
  'shape_exclude': 'Shape Exclude',
  'shape_intersect': 'Shape Intersect',
  'shape_subtract': 'Shape Subtract',
  'shape_union': 'Shape Union',
  'shapes': 'Shapes',
  'share': 'Share',
  'share_android': 'Share Android',
  'share_ios': 'Share iOS',
  'shell_script': 'Shell Script',
  'shield': 'Shield',
  'shopping_bag': 'Shopping Bag',
  'sim': 'SIM',
  'slide_add': 'Slide Add',
  'slide_content': 'Slide Content',
  'slide_eraser': 'Slide Eraser',
  'slide_grid': 'Slide Grid',
  'slide_hide': 'Slide Hide',
  'slide_layout': 'Slide Layout',
  'smartwatch': 'Smartwatch',
  'sound_source': 'Sound Source',
  'spacebar': 'Spacebar',
  'sport_baseball': 'Baseball',
  'sport_basketball': 'Basketball',
  'sport_soccer': 'Soccer',
  'spray_can': 'Spray Can',
  'square': 'Square',
  'square_hint': 'Square Hint',
  'square_multiple': 'Multiple Squares',
  'star': 'Star',
  'stop': 'Stop',
  'subtract': 'Subtract',
  'swift': 'Swift',
  'tab': 'Tab',
  'tablet': 'Tablet',
  'tag': 'Tag',
  'target': 'Target',
  'temperature': 'Temperature',
  'tent': 'Tent',
  'text': 'Text',
  'text_align_center': 'Text Align Center',
  'text_align_justify': 'Text Align Justify',
  'text_align_left': 'Text Align Left',
  'text_align_right': 'Text Align Right',
  'textbox': 'Textbox',
  'textbox_align_bottom': 'Textbox Align Bottom',
  'textbox_align_bottom_center': 'Textbox Align Bottom Center',
  'textbox_align_bottom_left': 'Textbox Align Bottom Left',
  'textbox_align_bottom_right': 'Textbox Align Bottom Right',
  'textbox_align_center': 'Textbox Align Center',
  'textbox_align_middle': 'Textbox Align Middle',
  'textbox_align_middle_left': 'Textbox Align Middle Left',
  'textbox_align_middle_right': 'Textbox Align Middle Right',
  'textbox_align_top': 'Textbox Align Top',
  'textbox_align_top_center': 'Textbox Align Top Center',
  'textbox_align_top_left': 'Textbox Align Top Left',
  'textbox_align_top_right': 'Textbox Align Top Right',
  'thinking': 'Thinking',
  'ticket': 'Ticket',
  'timer': 'Timer',
  'toggle_left': 'Toggle Left',
  'toggle_multiple': 'Toggle Multiple',
  'toggle_right': 'Toggle Right',
  'toolbox': 'Toolbox',
  'trophy': 'Trophy',
  'tv': 'TV',
  'typescript': 'TypeScript',
  'umbrella': 'Umbrella',
  'usb': 'USB',
  'usb_cable': 'USB Cable',
  'verified': 'Verified',
  'video': 'Video',
  'video_clip': 'Video Clip',
  'video_play_pause': 'Video Play Pause',
  'voicemail': 'Voicemail',
  'vote': 'Vote',
  'walkie_talkie': 'Walkie Talkie',
  'wallet': 'Wallet',
  'wand': 'Wand',
  'warning': 'Warning',
  'washer': 'Washer',
  'water': 'Water',
  'weather_blowing_snow': 'Blowing Snow',
  'weather_cloudy': 'Cloudy',
  'weather_rain': 'Rain',
  'weather_snow': 'Snow',
  'weather_snowflake': 'Snowflake',
  'weather_sunny': 'Sunny',
  'weather_thunderstorm': 'Thunderstorm',
  'web': 'Web',
  'wifi_1': 'WiFi 1',
  'wifi_2': 'WiFi 2',
  'wifi_3': 'WiFi 3',
  'wifi_4': 'WiFi 4',
  'windows': 'Windows',
  'wrench': 'Wrench',
  'xray': 'X-Ray',
  'zoom': 'Zoom',
  'zoom_in': 'Zoom In',
  'zoom_out': 'Zoom Out'
};
