name: refineui_system_icons
description: RefineUI System Icons for Flutter - A comprehensive icon library
version: 0.1.31
homepage: https://opensource.pelagornis.com
repository: https://github.com/pelagornis/refineui-system-icons

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  fonts:
    - family: RefineUI-System-Icons-Regular
      fonts:
        - asset: lib/fonts/refineui-system-icons-regular.ttf
    - family: RefineUI-System-Icons-Filled
      fonts:
        - asset: lib/fonts/refineui-system-icons-filled.ttf
