#!/usr/bin/env node

/**
 * React Native Icons Package - Icon Mapping Generator
 * 
 * This script reads the fonts/icon-mapping.json file and generates
 * TypeScript mapping files for the React Native package.
 */

const fs = require('fs');
const path = require('path');

// 경로 설정
const rootDir = path.resolve(__dirname, '../../../');
const mappingFile = path.join(rootDir, 'fonts/icon-mapping.json');
const outputFile = path.join(__dirname, '../src/generated-mapping.ts');

console.log('🔧 Generating React Native Icons mapping...');

try {
  // icon-mapping.json 읽기
  const mappingData = JSON.parse(fs.readFileSync(mappingFile, 'utf8'));
  
  // TypeScript 매핑 파일 생성
  let tsContent = `/**
 * Auto-generated icon mapping for React Native Icons package
 * Generated from fonts/icon-mapping.json
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 * Run: npm run generate-mapping
 */

export interface IconMapping {
  unicode: number;
  fontFamily: string;
  name: string;
  size: string;
  style: string;
}

export const ICON_MAPPING: Record<string, IconMapping> = {
`;

  // 모든 아이콘을 매핑에 추가
  Object.entries(mappingData.icons).forEach(([key, icon]) => {
    tsContent += `  "${key}": {
    unicode: ${icon.unicode},
    fontFamily: "${icon.style === 'regular' ? 'RefineUI-System-Icons-Regular' : 'RefineUI-System-Icons-Filled'}",
    name: "${icon.name}",
    size: "${icon.size}",
    style: "${icon.style}"
  },\n`;
  });

  tsContent += `};

export const ICON_NAMES = [
${Object.keys(mappingData.icons).map(key => `  "${key}"`).join(',\n')}
];

export function getIconUnicode(iconName: string): number | null {
  return ICON_MAPPING[iconName]?.unicode || null;
}

export function getIconFontFamily(iconName: string): string | null {
  return ICON_MAPPING[iconName]?.fontFamily || null;
}
`;

  // 파일 작성
  fs.writeFileSync(outputFile, tsContent);
  
  console.log(`✅ Generated mapping file: ${outputFile}`);
  console.log(`📊 Total icons: ${Object.keys(mappingData.icons).length}`);
  
} catch (error) {
  console.error('❌ Error generating mapping:', error);
  process.exit(1);
}
