name: Release Flutter Platform

on:
  push:
    tags:
      - "*"

jobs:
  release-flutter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.0"
          channel: "stable"

      - name: Configure Flutter
        run: |
          flutter config --no-analytics
          flutter config --no-cli-animations

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Get version
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version: $VERSION"

      - name: Update Flutter version
        run: |
          VERSION="${{ steps.get_version.outputs.version }}"

          # Update root package.json
          sed -i "s/\"version\": \".*\"/\"version\": \"$VERSION\"/" package.json

          # Update Flutter pubspec.yaml version
          sed -i "s/version:.*/version: $VERSION/" flutter/pubspec.yaml

          echo "Updated Flutter version to $VERSION"

      - name: Build Flutter platform
        run: |
          python3 scripts/generate_flutter_dart.py

      - name: Validate Flutter package
        run: |
          cd flutter
          flutter pub get
          # Only run analysis, no tests
          flutter analyze --no-fatal-infos --no-fatal-warnings

      - name: Publish Flutter package to pub.dev
        run: |
          cd flutter
          echo ${{ secrets.PUB_DEV_TOKEN }} | dart pub token add https://pub.dev
          dart pub publish --force
        env:
          PUB_DEV_TOKEN: ${{ secrets.PUB_DEV_TOKEN }}

      - name: Create Flutter Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          body: |
            ## 🎉 Flutter Platform Release ${{ steps.get_version.outputs.version }}

            ### 📦 Installation
            ```yaml
            # pubspec.yaml
            dependencies:
              refineui_system_icons: ^${{ steps.get_version.outputs.version }}
            ```

            ```dart
            import 'package:refineui_system_icons/refineui_system_icons.dart';
            ```

            ### 🦋 Features
            - Flutter-optimized components
            - Material Design compatible
            - Cross-platform consistency
            - 434+ icons with multiple sizes and styles
            - High-performance rendering

            ### 📁 Files
            Flutter source code and pubspec.yaml are attached below.
        env:
          GITHUB_TOKEN: ${{ secrets.PELAGORNIS }}
