name: Release Flutter Platform

on:
  push:
    tags:
      - "*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PELAGORNIS }}
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.0"
          channel: "stable"

      - name: Configure Flutter
        run: |
          flutter config --no-analytics
          flutter config --no-cli-animations

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Extract version from tag
        id: get_version
        run: |
          RAW_TAG=${GITHUB_REF#refs/tags/}
          VERSION=${RAW_TAG#v} # v 제거 (v0.1.35 → 0.1.35)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Detected version: $VERSION"

      - name: Update Flutter version
        run: |
          VERSION="${{ steps.get_version.outputs.version }}"
          sed -i "s/^version:.*/version: $VERSION/" flutter/pubspec.yaml
          echo "✅ Updated Flutter version to $VERSION"

      - name: Update Flutter CHANGELOG
        run: |
          VERSION="${{ steps.get_version.outputs.version }}"
          cat > /tmp/changelog_entry.md << EOF
          ## $VERSION

          - Updated all platform versions to $VERSION
          - Fixed React Native build errors and TypeScript conflicts
          - Improved icon generation scripts for better consistency
          - Enhanced package validation and publishing process
          - Fixed Git push conflicts in release workflows
          - Added concurrency controls to prevent workflow conflicts

          EOF

          cat /tmp/changelog_entry.md flutter/CHANGELOG.md > /tmp/new_changelog.md
          mv /tmp/new_changelog.md flutter/CHANGELOG.md
          rm -f /tmp/changelog_entry.md
          echo "✅ Updated Flutter CHANGELOG.md with version $VERSION"

      - name: Commit version & changelog to main
        run: |
          VERSION="${{ steps.get_version.outputs.version }}"
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add flutter/pubspec.yaml flutter/CHANGELOG.md
          git commit -m "chore(flutter): release $VERSION [skip ci]"
          git push origin HEAD:main
          echo "✅ Committed version bump to main"

      - name: Build Flutter platform
        run: |
          python3 scripts/generate_flutter_dart.py

      - name: Get Flutter dependencies
        run: |
          cd flutter
          flutter pub get
          cd example
          flutter pub get

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: "Flutter Platform Release ${{ steps.get_version.outputs.version }}"
          body: |
            ## 🎉 Flutter Platform Release ${{ steps.get_version.outputs.version }}

            ### 📦 Installation
            ```yaml
            dependencies:
              refineui_system_icons: ^${{ steps.get_version.outputs.version }}
            ```

            ### 🦋 Features
            - Flutter-optimized components
            - Material Design compatible
            - Cross-platform consistency
            - 434+ icons with multiple sizes and styles
            - High-performance rendering
        env:
          GITHUB_TOKEN: ${{ secrets.PELAGORNIS }}

      - name: Publish to pub.dev
        run: |
          cd flutter
          flutter pub publish --force
